"""from scratch

Revision ID: e19ebbc6acf5
Revises:
Create Date: 2025-04-10 14:59:09.635533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e19ebbc6acf5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regular_market",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_desc", sa.Text(), nullable=False),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("tta", sa.Float(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("ltp", sa.Float(), nullable=False),
        sa.Column("lty", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("regular_market")
    # ### end Alembic commands ###
